export const SCAN_TEST_PAYLOAD_ABC = "NAPOLITRANS-TEST-ABC123";
export const SCAN_TEST_PAYLOAD_MATRIX = "NAPOLITRANS-TEST-MATRIX";

export const SCAN_TEST_PAYLOADS = [
  SCAN_TEST_PAYLOAD_ABC,
  SCAN_TEST_PAYLOAD_MATRIX,
] as const;
